window.AppConfig = {
  SUPABASE_URL: 'https://rkyvtezgiqlqyatbflmq.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreXZ0ZXpnaXFscXlhdGJmbG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM3Mjg1ODIsImV4cCI6MjA5OTMwNDU4Mn0.xtvizUKPrKOYwB8KeLWHGlIeQigySpf8o8VLSfdpg2o'
};
